### PR TITLE
Generating fixed vulnerabilities during build process

### PR DESCRIPTION
**Pull request by oblitorum**

### CODE REVIEW

**Comment by oblitorum** [comment]
@gordan-bobic 

There is a large diff of `grafana-yarn.lock`, it's the dependency lock files of `Grafana`, I updated it because the previous version isn't vulnerability-fixed, I just found out when I was trying to list the fixed vulnerabilities of `Grafana`, sorry about that. Below is the whole diff of it.

[grafana-yarn.lock.diff.txt](https://github.com/shatteredsilicon/ssm-submodules/files/9374003/grafana-yarn.lock.diff.txt)

**Comment by gordan-bobic** [comment]
Should docs/fixed-vulnerabilities/*.md be in git? Or should they be generated at build time only?
I am leaning toward having them as build time artifacts, and not in git.

@niall-daley what is your opinion?

**Comment by oblitorum** [comment]
I'm not very sure, do you expect that it can update these docs automatically in the future, if so maybe putting them in git is ok. For example, in the future you can add a step to CICD to check if these docs have updates, if so commit the changes.
This can be done whether it's in git or not though, so I'm ok in both cases.

**Comment by gordan-bobic** [comment]
I'd like @niall-daley 's input on this because he will be more involved in the CICD things with this.

**Comment by niall-daley** [comment]
It depends on what the purpose of the documents is, but it sounds like if they can be generated at run time that might be the cleanest way to go as it'll keep them in sync with what is actually being built.

**Comment by gordan-bobic** [comment]
OK, please omit them from git, then.

**Comment by oblitorum** [comment]
OK, I added that directory to `.gitignore`

**Pull request merged**
