### PR TITLE
Remove additional 'pushing to docker hub' feature

### PR DESCRIPTION
**Pull request by oblitorum**
cc @niall-daley

### CODE REVIEW

**Comment by gordan-bobic** [comment]
Can we combine into this pull the separate script that does the removed functionality?

**Comment by oblitorum** [comment]
Sure, but is it necessary to create a separate script? It's basically just a `docker push` command

**Comment by gordan-bobic** [comment]
@niall-daley ? What do you think? Is there other stuff that needs to happen? Signing, something like that?

**Comment by niall-daley** [comment]
All of the actions like pushing to dockerhub and signing RPMs should be completely separate and should not be in this repository at all. I'll take a look at those when I get to building an actual build pipeline for this project. As @oblitorum says, the push is pretty trivial, and the signing will need to be done in a very secure way so can't be done here.

We might want to break the build up a bit more to make it more managable, but we can talk about that later.

@oblitorum One thing I have noticed, and I'll raise as a separate issue is that the Makefile currently updates all the modules to their latest version. We should not do that as it changes the files the user has checked out. You should just update to the correct commit on each submodule, then commit that. That way anyone checking out a specific version of ssm-submodules will get exactly the same code.

**Comment by oblitorum** [comment]
Good idea! It's true that current build script always build the latest tag of each submodule.

@gordan-bobic If you agree with this, I'll change it this way in another pr.

> One thing I have noticed, and I'll raise as a separate issue is that the Makefile currently updates all the modules to their latest version. We should not do that as it changes the files the user has checked out. You should just update to the correct commit on each submodule, then commit that. That way anyone checking out a specific version of ssm-submodules will get exactly the same code.

**Pull request merged**
