### PR TITLE
Retrieve 3rd-party package build files from ssm-server-packaging repo

### PR DESCRIPTION
**Pull request by oblitorum**

### CODE REVIEW

**Comment by gordan-bobic** [comment]
sources/grafana/grafana-node_modules-v5.4.5.tar.gz shouldn't be a big tarball in git. This should be fetched from upstream by the build process at src.rpm build time.

**Comment by oblitorum** [comment]
There is one big grafana path file https://github.com/shatteredsilicon/ssm-submodules/pull/4/files#diff-81c33175426cb806bad17745abc8d77f4a6dddc2d35228c111a464333d947b1d

I put it here in comment (it's a diff/patch file, but github doesn't support it, so I change the extension to .txt)
[0001-NPM-audit-fix.txt](https://github.com/shatteredsilicon/ssm-submodules/files/9267591/0001-NPM-audit-fix.txt)

**Comment by gordan-bobic** [comment]
sources/grafana/node-sass-node_modules-v4.14.1.tar.gz
shouldn't be in our repository either, needs to be fetched from upstream at src.rpm build time.

**Comment by oblitorum** [comment]
> sources/grafana/grafana-node_modules-v5.4.5.tar.gz shouldn't be a big tarball in git. This should be fetched from upstream by the build process at src.rpm build time.

Oh sorry, I thought only self-maintained repos need to pull dependencies on src.rpm build time, will change that

**Comment by gordan-bobic** [comment]
sources/percona-toolkit/percona-toolkit-vendor-v3.3.1.tar.gz
shouldn't be in our repository either, needs to be fetched from upstream at src.rpm build time.
Also, this is out of date, current version is 3.4.0

**Comment by gordan-bobic** [comment]
And this:
sources/prometheus/prometheus-vendor-v2.35.0.tar.gz

**Comment by oblitorum** [comment]
> sources/percona-toolkit/percona-toolkit-vendor-v3.3.1.tar.gz shouldn't be in our repository either, needs to be fetched from upstream at src.rpm build time. Also, this is out of date, current version is 3.4.0

OK, will update it

**Comment by oblitorum** [comment]
OK, ready to be merged

**Comment by oblitorum** [comment]
OK, ready to be merged

**Pull request merged**
